import { useRouter } from "next/router";

import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();
  const cardList = [
    { title: "Alunos", path: "/students" },
    { title: "Cursos", path: "/courses" },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Bem-vindo ao projeto AF!</h1>

        <div className="flex space-x-6 p-6">
          {cardList.map((cardItem) => (
            <div
              className="w-1/2 bg-white rounded-lg shadow-md p-6 cursor-pointer"
              onClick={() => router.push(cardItem.path)}
            >
              <h2 className="text-xl font-bold mb-2">{cardItem?.title}</h2>
              <p className="text-gray-600">
                Clique no card para visualizar mais
              </p>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        Testemunhas de Turing @{new Date().getFullYear()}
      </footer>
    </div>
  );
}
